Remove DNNCorp copyright
dnnsoftware/Language-Pack-FR-FR pull request #10
Opened 2020-06-07 12:06 UTC by EPTamminga

Close #9

2020-06-08 18:36 UTC, valadas requested changes
I would prefer this wording

2020-06-08 18:36 UTC, valadas commented on Resources/Portals/_default/Blank Website.template.fr-FR.resx
> +    <value xml:space="preserve">Copyright [year] mon site internet</value>
```suggestion
    <value xml:space="preserve">Copyright [year] mon site web</value>
```

2020-06-08 18:36 UTC, valadas commented on Resources/Portals/_default/Default Website.template.fr-FR.resx
> +    <value xml:space="preserve">Copyright [year] mon site internet</value>
```suggestion
    <value xml:space="preserve">Copyright [year] mon site web</value>
```

2020-06-09 07:47 UTC, EPTamminga commented
@valadas _Your wish is my command. Consider it done_.

2020-06-09 17:50 UTC, EPTamminga commented on Resources/Portals/_default/Default Website.template.fr-FR.resx
> +    <value xml:space="preserve">Copyright [year] mon site internet</value>
Done

2020-06-12 05:45 UTC, valadas commented
Thank you sir!

2020-06-12 05:46 UTC, valadas approved these changes

2020-06-12 05:46 UTC, merged