Some fixes and suggested changes
dnnsoftware/Language-Pack-FR-FR pull request #21
Opened 2024-03-12 16:58 UTC by stetard

2024-03-12 23:30 UTC, valadas requested changes
Looks good except the noted corrections which you can approve in the browser if you agree.

2024-03-12 23:30 UTC, valadas commented on Resources/DesktopModules/Admin/Security/App_LocalResources/DataConsent.ascx.fr-FR.resx
> +    <value>Vos données personnelles vont être anonymisées. Après cela, ces données ne seront plus reliées à votre identité et il ne vous ne sera plus possible de vous reconnecter avec ce compte. Souh
```suggestion
    <value>Vos données personnelles vont être anonymisées. Après cela, ces données ne seront plus reliées à votre identité et il ne vous sera plus possible de vous reconnecter avec ce compte. Souhaitez-vous continuer ?</value>
```

2024-03-12 23:30 UTC, valadas commented on Resources/DesktopModules/Admin/Security/App_LocalResources/DataConsent.ascx.fr-FR.resx
> +    <value>Vos données personnelles vont être supprimées de ce site très prochainement. Après cela elles seront définitivement perdues. De plus, il ne vous ne sera plus possible de vous reconnecter a
```suggestion
    <value>Vos données personnelles vont être supprimées de ce site très prochainement. Après cela elles seront définitivement perdues. De plus, il ne vous sera plus possible de vous reconnecter avec ce compte. Souhaitez-vous continuer ?</value>
```

2024-03-12 23:30 UTC, valadas commented on Resources/DesktopModules/Admin/Security/App_LocalResources/DataConsent.ascx.fr-FR.resx
> +    <value>Vos données personnelles vont être supprimées de ce site immédiatement. Après cela elles seront définitivement perdues. De plus, il ne vous ne sera plus possible de vous reconnecter avec c
```suggestion
    <value>Vos données personnelles vont être supprimées de ce site immédiatement. Après cela elles seront définitivement perdues. De plus, il ne vous sera plus possible de vous reconnecter avec ce compte. Souhaitez-vous continuer ?</value>
```

2024-03-12 23:30 UTC, valadas commented on Resources/DesktopModules/Admin/Security/App_LocalResources/DataConsent.ascx.fr-FR.resx
> +    <value>Nous nous efforcerons de supprimer vos données personnelles de ce site très prochainement. Après cela elles seront définitivement perdues. De plus, il ne vous ne sera plus possible de vous
```suggestion
    <value>Nous nous efforcerons de supprimer vos données personnelles de ce site très prochainement. Après cela elles seront définitivement perdues. De plus, il ne vous sera plus possible de vous reconnecter avec ce compte. Souhaitez-vous continuer ?</value>
```

2024-03-13 09:21 UTC, stetard commented
Hi Daniel,
First, sorry for the mistakes.
I'm not sure about the process of validating your suggested changes. I hope it's correct now.
Just a question: yesterday, I spent few hours to try to complete the french language pack on a fresh DNN 9.13.3 install using the dedicated DNN interface. When I tried to copy the changes into the GitHub ressources repository, I got the surprise that the most was already done.
I'm wondering why the latest release didn't installed the latest french language pack. I think it could be better if the latest language pack is automaticaly provided. It seems that only the 9.2.0 is available in the proposed packages instead of the 9.9.1 which is better.

2024-03-13 18:35 UTC, valadas commented
> I'm not sure about the process of validating your suggested changes. I hope it's correct now.

Exactly what you did, just accepting in the browser. For some more complex changes (like code that would also need testing and stuff) it could be additional commits pushed to the same branch.

> I'm wondering why the latest release didn't installed the latest french language pack

Because no release was created, I had no time to really test out the language pack since last release but also did not see anything crazy come in since then. If you feel this is 9.13.3 worth, I can create a release...

2024-03-15 18:17 UTC, merged