Uopdate license in all packages to ,NET Foundation standard
dnnsoftware/Language-Pack-FR-FR pull request #8
Opened 2020-06-05 07:35 UTC by EPTamminga

Close #7

2020-06-05 15:17 UTC, valadas requested changes
Thanks @EPTamminga The .gitignore is missing a line for the actual resource files though, can you add !*.fr-FR.resx or some such

2020-06-05 15:46 UTC, EPTamminga commented
Sorry @valadas , you had a different .gitgnore than the other LP repo's and I tried to fit in the standard from the others, but I missed a line.
It's corrected with an additional commit.

2020-06-08 18:32 UTC, valadas approved these changes

2020-06-08 18:32 UTC, valadas commented
Thank you @EPTamminga

2020-06-08 18:32 UTC, merged